services:
  - type: web
    name: furima-45691-web
    env: ruby
    plan: free
    region: oregon
    branch: main
    repo: https://github.com/nitouhei9/furima-45691
    buildCommand: bundle install && yarn install && bundle exec rails assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: furima-db
          property: connectionString

  - type: worker
    name: furima-45691-migrate
    env: ruby
    plan: free
    region: oregon
    branch: main
    repo: https://github.com/nitouhei9/furima-45691
    startCommand: bundle exec rails db:migrate
    autoDeploy: false
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: furima-db
          property: connectionString

databases:
  - name: furima-db
    plan: free
    region: oregon
    databaseName: furima_45691_production
    user: furima_user
