default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: sqlite3
  username: root
  password:
  host: localhost
  database: furima-45691_development

test:
  <<: *default
  adapter: sqlite3
  username: root
  password:
  host: localhost
  database: furima-45691_test

production:
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  database: furima-45691_production
  username: root
  password: '2222'
  host: 127.0.0.1